// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: device/v1/device.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Platform int32

const (
	Platform_web     Platform = 0
	Platform_android Platform = 1
	Platform_ios     Platform = 2
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "web",
		1: "android",
		2: "ios",
	}
	Platform_value = map[string]int32{
		"web":     0,
		"android": 1,
		"ios":     2,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_device_v1_device_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_device_v1_device_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{0}
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Platform      Platform               `protobuf:"varint,2,opt,name=platform,proto3,enum=device.v1.Platform" json:"platform,omitempty"`
	AppVersion    string                 `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_device_v1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_web
}

func (x *Device) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type SetFcmTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      *UuId                  `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	NewFcmToken   string                 `protobuf:"bytes,2,opt,name=new_fcm_token,json=newFcmToken,proto3" json:"new_fcm_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFcmTokenRequest) Reset() {
	*x = SetFcmTokenRequest{}
	mi := &file_device_v1_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFcmTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFcmTokenRequest) ProtoMessage() {}

func (x *SetFcmTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFcmTokenRequest.ProtoReflect.Descriptor instead.
func (*SetFcmTokenRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{1}
}

func (x *SetFcmTokenRequest) GetDeviceId() *UuId {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *SetFcmTokenRequest) GetNewFcmToken() string {
	if x != nil {
		return x.NewFcmToken
	}
	return ""
}

var File_device_v1_device_proto protoreflect.FileDescriptor

const file_device_v1_device_proto_rawDesc = "" +
	"\n" +
	"\x16device/v1/device.proto\x12\tdevice.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12uuid/v1/uuid.proto\"n\n" +
	"\x06Device\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x13.device.v1.PlatformR\bplatform\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\"d\n" +
	"\x12SetFcmTokenRequest\x12*\n" +
	"\tdevice_id\x18\x01 \x01(\v2\r.uuid.v1.UuIdR\bdeviceId\x12\"\n" +
	"\rnew_fcm_token\x18\x02 \x01(\tR\vnewFcmToken*)\n" +
	"\bPlatform\x12\a\n" +
	"\x03web\x10\x00\x12\v\n" +
	"\aandroid\x10\x01\x12\a\n" +
	"\x03ios\x10\x022U\n" +
	"\rDeviceService\x12D\n" +
	"\vSetFcmToken\x12\x1d.device.v1.SetFcmTokenRequest\x1a\x16.google.protobuf.EmptyB\x06Z\x04./v1b\x06proto3"

var (
	file_device_v1_device_proto_rawDescOnce sync.Once
	file_device_v1_device_proto_rawDescData []byte
)

func file_device_v1_device_proto_rawDescGZIP() []byte {
	file_device_v1_device_proto_rawDescOnce.Do(func() {
		file_device_v1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_v1_device_proto_rawDesc), len(file_device_v1_device_proto_rawDesc)))
	})
	return file_device_v1_device_proto_rawDescData
}

var file_device_v1_device_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_device_v1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_device_v1_device_proto_goTypes = []any{
	(Platform)(0),              // 0: device.v1.Platform
	(*Device)(nil),             // 1: device.v1.Device
	(*SetFcmTokenRequest)(nil), // 2: device.v1.SetFcmTokenRequest
	(*UuId)(nil),               // 3: uuid.v1.UuId
	(*emptypb.Empty)(nil),      // 4: google.protobuf.Empty
}
var file_device_v1_device_proto_depIdxs = []int32{
	0, // 0: device.v1.Device.platform:type_name -> device.v1.Platform
	3, // 1: device.v1.SetFcmTokenRequest.device_id:type_name -> uuid.v1.UuId
	2, // 2: device.v1.DeviceService.SetFcmToken:input_type -> device.v1.SetFcmTokenRequest
	4, // 3: device.v1.DeviceService.SetFcmToken:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_device_v1_device_proto_init() }
func file_device_v1_device_proto_init() {
	if File_device_v1_device_proto != nil {
		return
	}
	file_uuid_v1_uuid_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_v1_device_proto_rawDesc), len(file_device_v1_device_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_v1_device_proto_goTypes,
		DependencyIndexes: file_device_v1_device_proto_depIdxs,
		EnumInfos:         file_device_v1_device_proto_enumTypes,
		MessageInfos:      file_device_v1_device_proto_msgTypes,
	}.Build()
	File_device_v1_device_proto = out.File
	file_device_v1_device_proto_goTypes = nil
	file_device_v1_device_proto_depIdxs = nil
}
