// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: auth/v1/auth.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnboardService_PublicKeyOnboard_FullMethodName       = "/auth.v1.OnboardService/PublicKeyOnboard"
	OnboardService_VerifyOnboardPublicKey_FullMethodName = "/auth.v1.OnboardService/VerifyOnboardPublicKey"
	OnboardService_PasswordOnboard_FullMethodName        = "/auth.v1.OnboardService/PasswordOnboard"
)

// OnboardServiceClient is the client API for OnboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NOTE: ONBOARD
type OnboardServiceClient interface {
	PublicKeyOnboard(ctx context.Context, in *PublicKeyOnboardRequest, opts ...grpc.CallOption) (*PublicKeyOnboardResponse, error)
	VerifyOnboardPublicKey(ctx context.Context, in *VerifyOnboardPublicKeyRequest, opts ...grpc.CallOption) (*VerifyOnboardPublicKeyRequest, error)
	PasswordOnboard(ctx context.Context, in *PasswordOnboardRequest, opts ...grpc.CallOption) (*PasswordOnboardResponse, error)
}

type onboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnboardServiceClient(cc grpc.ClientConnInterface) OnboardServiceClient {
	return &onboardServiceClient{cc}
}

func (c *onboardServiceClient) PublicKeyOnboard(ctx context.Context, in *PublicKeyOnboardRequest, opts ...grpc.CallOption) (*PublicKeyOnboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicKeyOnboardResponse)
	err := c.cc.Invoke(ctx, OnboardService_PublicKeyOnboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardServiceClient) VerifyOnboardPublicKey(ctx context.Context, in *VerifyOnboardPublicKeyRequest, opts ...grpc.CallOption) (*VerifyOnboardPublicKeyRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyOnboardPublicKeyRequest)
	err := c.cc.Invoke(ctx, OnboardService_VerifyOnboardPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardServiceClient) PasswordOnboard(ctx context.Context, in *PasswordOnboardRequest, opts ...grpc.CallOption) (*PasswordOnboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasswordOnboardResponse)
	err := c.cc.Invoke(ctx, OnboardService_PasswordOnboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnboardServiceServer is the server API for OnboardService service.
// All implementations must embed UnimplementedOnboardServiceServer
// for forward compatibility.
//
// NOTE: ONBOARD
type OnboardServiceServer interface {
	PublicKeyOnboard(context.Context, *PublicKeyOnboardRequest) (*PublicKeyOnboardResponse, error)
	VerifyOnboardPublicKey(context.Context, *VerifyOnboardPublicKeyRequest) (*VerifyOnboardPublicKeyRequest, error)
	PasswordOnboard(context.Context, *PasswordOnboardRequest) (*PasswordOnboardResponse, error)
	mustEmbedUnimplementedOnboardServiceServer()
}

// UnimplementedOnboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnboardServiceServer struct{}

func (UnimplementedOnboardServiceServer) PublicKeyOnboard(context.Context, *PublicKeyOnboardRequest) (*PublicKeyOnboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicKeyOnboard not implemented")
}
func (UnimplementedOnboardServiceServer) VerifyOnboardPublicKey(context.Context, *VerifyOnboardPublicKeyRequest) (*VerifyOnboardPublicKeyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyOnboardPublicKey not implemented")
}
func (UnimplementedOnboardServiceServer) PasswordOnboard(context.Context, *PasswordOnboardRequest) (*PasswordOnboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasswordOnboard not implemented")
}
func (UnimplementedOnboardServiceServer) mustEmbedUnimplementedOnboardServiceServer() {}
func (UnimplementedOnboardServiceServer) testEmbeddedByValue()                        {}

// UnsafeOnboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnboardServiceServer will
// result in compilation errors.
type UnsafeOnboardServiceServer interface {
	mustEmbedUnimplementedOnboardServiceServer()
}

func RegisterOnboardServiceServer(s grpc.ServiceRegistrar, srv OnboardServiceServer) {
	// If the following call pancis, it indicates UnimplementedOnboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnboardService_ServiceDesc, srv)
}

func _OnboardService_PublicKeyOnboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicKeyOnboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardServiceServer).PublicKeyOnboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardService_PublicKeyOnboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardServiceServer).PublicKeyOnboard(ctx, req.(*PublicKeyOnboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnboardService_VerifyOnboardPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOnboardPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardServiceServer).VerifyOnboardPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardService_VerifyOnboardPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardServiceServer).VerifyOnboardPublicKey(ctx, req.(*VerifyOnboardPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnboardService_PasswordOnboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordOnboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardServiceServer).PasswordOnboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardService_PasswordOnboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardServiceServer).PasswordOnboard(ctx, req.(*PasswordOnboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OnboardService_ServiceDesc is the grpc.ServiceDesc for OnboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.OnboardService",
	HandlerType: (*OnboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublicKeyOnboard",
			Handler:    _OnboardService_PublicKeyOnboard_Handler,
		},
		{
			MethodName: "VerifyOnboardPublicKey",
			Handler:    _OnboardService_VerifyOnboardPublicKey_Handler,
		},
		{
			MethodName: "PasswordOnboard",
			Handler:    _OnboardService_PasswordOnboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}

const (
	AuthService_DiscoverLogin_FullMethodName        = "/auth.v1.AuthService/DiscoverLogin"
	AuthService_VerifyLoginPublicKey_FullMethodName = "/auth.v1.AuthService/VerifyLoginPublicKey"
	AuthService_PasswordLogin_FullMethodName        = "/auth.v1.AuthService/PasswordLogin"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NOTE: AUTHENTICATION
type AuthServiceClient interface {
	DiscoverLogin(ctx context.Context, in *DiscoverLoginRequest, opts ...grpc.CallOption) (*DiscoverLoginResponse, error)
	VerifyLoginPublicKey(ctx context.Context, in *VerifyLoginPublicKeyRequest, opts ...grpc.CallOption) (*VerifyLoginPublicKeyResponse, error)
	PasswordLogin(ctx context.Context, in *PasswordLoginRequest, opts ...grpc.CallOption) (*PasswordLoginResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) DiscoverLogin(ctx context.Context, in *DiscoverLoginRequest, opts ...grpc.CallOption) (*DiscoverLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_DiscoverLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyLoginPublicKey(ctx context.Context, in *VerifyLoginPublicKeyRequest, opts ...grpc.CallOption) (*VerifyLoginPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyLoginPublicKeyResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyLoginPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) PasswordLogin(ctx context.Context, in *PasswordLoginRequest, opts ...grpc.CallOption) (*PasswordLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasswordLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_PasswordLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// NOTE: AUTHENTICATION
type AuthServiceServer interface {
	DiscoverLogin(context.Context, *DiscoverLoginRequest) (*DiscoverLoginResponse, error)
	VerifyLoginPublicKey(context.Context, *VerifyLoginPublicKeyRequest) (*VerifyLoginPublicKeyResponse, error)
	PasswordLogin(context.Context, *PasswordLoginRequest) (*PasswordLoginResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) DiscoverLogin(context.Context, *DiscoverLoginRequest) (*DiscoverLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoverLogin not implemented")
}
func (UnimplementedAuthServiceServer) VerifyLoginPublicKey(context.Context, *VerifyLoginPublicKeyRequest) (*VerifyLoginPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyLoginPublicKey not implemented")
}
func (UnimplementedAuthServiceServer) PasswordLogin(context.Context, *PasswordLoginRequest) (*PasswordLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasswordLogin not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_DiscoverLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DiscoverLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_DiscoverLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DiscoverLogin(ctx, req.(*DiscoverLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyLoginPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyLoginPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyLoginPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyLoginPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyLoginPublicKey(ctx, req.(*VerifyLoginPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_PasswordLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).PasswordLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_PasswordLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).PasswordLogin(ctx, req.(*PasswordLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DiscoverLogin",
			Handler:    _AuthService_DiscoverLogin_Handler,
		},
		{
			MethodName: "VerifyLoginPublicKey",
			Handler:    _AuthService_VerifyLoginPublicKey_Handler,
		},
		{
			MethodName: "PasswordLogin",
			Handler:    _AuthService_PasswordLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}

const (
	ReAuthService_RefreshSession_FullMethodName  = "/auth.v1.ReAuthService/RefreshSession"
	ReAuthService_ReAuth_FullMethodName          = "/auth.v1.ReAuthService/ReAuth"
	ReAuthService_VerifyPublicKey_FullMethodName = "/auth.v1.ReAuthService/VerifyPublicKey"
	ReAuthService_PasswordReAuth_FullMethodName  = "/auth.v1.ReAuthService/PasswordReAuth"
)

// ReAuthServiceClient is the client API for ReAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NOTE: RE-AUTH
type ReAuthServiceClient interface {
	RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*RefreshSessionResponse, error)
	ReAuth(ctx context.Context, in *ReAuthRequest, opts ...grpc.CallOption) (*ReAuthResponse, error)
	VerifyPublicKey(ctx context.Context, in *VerifyPublicKeyRequest, opts ...grpc.CallOption) (*VerifyPublicKeyResponse, error)
	PasswordReAuth(ctx context.Context, in *PasswordReAuthRequest, opts ...grpc.CallOption) (*PasswordReAuthResponse, error)
}

type reAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReAuthServiceClient(cc grpc.ClientConnInterface) ReAuthServiceClient {
	return &reAuthServiceClient{cc}
}

func (c *reAuthServiceClient) RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*RefreshSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshSessionResponse)
	err := c.cc.Invoke(ctx, ReAuthService_RefreshSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reAuthServiceClient) ReAuth(ctx context.Context, in *ReAuthRequest, opts ...grpc.CallOption) (*ReAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReAuthResponse)
	err := c.cc.Invoke(ctx, ReAuthService_ReAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reAuthServiceClient) VerifyPublicKey(ctx context.Context, in *VerifyPublicKeyRequest, opts ...grpc.CallOption) (*VerifyPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPublicKeyResponse)
	err := c.cc.Invoke(ctx, ReAuthService_VerifyPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reAuthServiceClient) PasswordReAuth(ctx context.Context, in *PasswordReAuthRequest, opts ...grpc.CallOption) (*PasswordReAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasswordReAuthResponse)
	err := c.cc.Invoke(ctx, ReAuthService_PasswordReAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReAuthServiceServer is the server API for ReAuthService service.
// All implementations must embed UnimplementedReAuthServiceServer
// for forward compatibility.
//
// NOTE: RE-AUTH
type ReAuthServiceServer interface {
	RefreshSession(context.Context, *RefreshSessionRequest) (*RefreshSessionResponse, error)
	ReAuth(context.Context, *ReAuthRequest) (*ReAuthResponse, error)
	VerifyPublicKey(context.Context, *VerifyPublicKeyRequest) (*VerifyPublicKeyResponse, error)
	PasswordReAuth(context.Context, *PasswordReAuthRequest) (*PasswordReAuthResponse, error)
	mustEmbedUnimplementedReAuthServiceServer()
}

// UnimplementedReAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReAuthServiceServer struct{}

func (UnimplementedReAuthServiceServer) RefreshSession(context.Context, *RefreshSessionRequest) (*RefreshSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSession not implemented")
}
func (UnimplementedReAuthServiceServer) ReAuth(context.Context, *ReAuthRequest) (*ReAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReAuth not implemented")
}
func (UnimplementedReAuthServiceServer) VerifyPublicKey(context.Context, *VerifyPublicKeyRequest) (*VerifyPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPublicKey not implemented")
}
func (UnimplementedReAuthServiceServer) PasswordReAuth(context.Context, *PasswordReAuthRequest) (*PasswordReAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasswordReAuth not implemented")
}
func (UnimplementedReAuthServiceServer) mustEmbedUnimplementedReAuthServiceServer() {}
func (UnimplementedReAuthServiceServer) testEmbeddedByValue()                       {}

// UnsafeReAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReAuthServiceServer will
// result in compilation errors.
type UnsafeReAuthServiceServer interface {
	mustEmbedUnimplementedReAuthServiceServer()
}

func RegisterReAuthServiceServer(s grpc.ServiceRegistrar, srv ReAuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedReAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReAuthService_ServiceDesc, srv)
}

func _ReAuthService_RefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReAuthServiceServer).RefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReAuthService_RefreshSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReAuthServiceServer).RefreshSession(ctx, req.(*RefreshSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReAuthService_ReAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReAuthServiceServer).ReAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReAuthService_ReAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReAuthServiceServer).ReAuth(ctx, req.(*ReAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReAuthService_VerifyPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReAuthServiceServer).VerifyPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReAuthService_VerifyPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReAuthServiceServer).VerifyPublicKey(ctx, req.(*VerifyPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReAuthService_PasswordReAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordReAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReAuthServiceServer).PasswordReAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReAuthService_PasswordReAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReAuthServiceServer).PasswordReAuth(ctx, req.(*PasswordReAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReAuthService_ServiceDesc is the grpc.ServiceDesc for ReAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.ReAuthService",
	HandlerType: (*ReAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefreshSession",
			Handler:    _ReAuthService_RefreshSession_Handler,
		},
		{
			MethodName: "ReAuth",
			Handler:    _ReAuthService_ReAuth_Handler,
		},
		{
			MethodName: "VerifyPublicKey",
			Handler:    _ReAuthService_VerifyPublicKey_Handler,
		},
		{
			MethodName: "PasswordReAuth",
			Handler:    _ReAuthService_PasswordReAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}
