// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: auth/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NOTE: COMMON
type PublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signed        []byte                 `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
	UserHandle    *string                `protobuf:"bytes,2,opt,name=user_handle,json=userHandle,proto3,oneof" json:"user_handle,omitempty"`
	DeviceInfo    *Device                `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyRequest) Reset() {
	*x = PublicKeyRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyRequest) ProtoMessage() {}

func (x *PublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyRequest.ProtoReflect.Descriptor instead.
func (*PublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKeyRequest) GetSigned() []byte {
	if x != nil {
		return x.Signed
	}
	return nil
}

func (x *PublicKeyRequest) GetUserHandle() string {
	if x != nil && x.UserHandle != nil {
		return *x.UserHandle
	}
	return ""
}

func (x *PublicKeyRequest) GetDeviceInfo() *Device {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type PublicKeyOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     []byte                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	ValidUntil    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyOption) Reset() {
	*x = PublicKeyOption{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyOption) ProtoMessage() {}

func (x *PublicKeyOption) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyOption.ProtoReflect.Descriptor instead.
func (*PublicKeyOption) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *PublicKeyOption) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *PublicKeyOption) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

type UserSession struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           []byte                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	UserHandle            string                 `protobuf:"bytes,2,opt,name=user_handle,json=userHandle,proto3" json:"user_handle,omitempty"`
	DisplayName           string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	RefreshToken          []byte                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TotalPasskey          *uint32                `protobuf:"varint,5,opt,name=total_passkey,json=totalPasskey,proto3,oneof" json:"total_passkey,omitempty"`
	LastPasswordUpdated   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_password_updated,json=lastPasswordUpdated,proto3,oneof" json:"last_password_updated,omitempty"`
	AccessTokenExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	DeviceId              *UuId                  `protobuf:"bytes,9,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserSession) Reset() {
	*x = UserSession{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSession) ProtoMessage() {}

func (x *UserSession) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSession.ProtoReflect.Descriptor instead.
func (*UserSession) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *UserSession) GetAccessToken() []byte {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *UserSession) GetUserHandle() string {
	if x != nil {
		return x.UserHandle
	}
	return ""
}

func (x *UserSession) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserSession) GetRefreshToken() []byte {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

func (x *UserSession) GetTotalPasskey() uint32 {
	if x != nil && x.TotalPasskey != nil {
		return *x.TotalPasskey
	}
	return 0
}

func (x *UserSession) GetLastPasswordUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPasswordUpdated
	}
	return nil
}

func (x *UserSession) GetAccessTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return nil
}

func (x *UserSession) GetRefreshTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return nil
}

func (x *UserSession) GetDeviceId() *UuId {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

type PublicKeyOnboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserHandle    string                 `protobuf:"bytes,1,opt,name=user_handle,json=userHandle,proto3" json:"user_handle,omitempty"`
	DisplayName   *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyOnboardRequest) Reset() {
	*x = PublicKeyOnboardRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyOnboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyOnboardRequest) ProtoMessage() {}

func (x *PublicKeyOnboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyOnboardRequest.ProtoReflect.Descriptor instead.
func (*PublicKeyOnboardRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *PublicKeyOnboardRequest) GetUserHandle() string {
	if x != nil {
		return x.UserHandle
	}
	return ""
}

func (x *PublicKeyOnboardRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

type PublicKeyOnboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Option        *PublicKeyOption       `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyOnboardResponse) Reset() {
	*x = PublicKeyOnboardResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyOnboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyOnboardResponse) ProtoMessage() {}

func (x *PublicKeyOnboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyOnboardResponse.ProtoReflect.Descriptor instead.
func (*PublicKeyOnboardResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *PublicKeyOnboardResponse) GetOption() *PublicKeyOption {
	if x != nil {
		return x.Option
	}
	return nil
}

type VerifyOnboardPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *PublicKeyRequest      `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOnboardPublicKeyRequest) Reset() {
	*x = VerifyOnboardPublicKeyRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOnboardPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOnboardPublicKeyRequest) ProtoMessage() {}

func (x *VerifyOnboardPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOnboardPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*VerifyOnboardPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyOnboardPublicKeyRequest) GetRequest() *PublicKeyRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type VerifyOnboardPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserSession   *UserSession           `protobuf:"bytes,1,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOnboardPublicKeyResponse) Reset() {
	*x = VerifyOnboardPublicKeyResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOnboardPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOnboardPublicKeyResponse) ProtoMessage() {}

func (x *VerifyOnboardPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOnboardPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*VerifyOnboardPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyOnboardPublicKeyResponse) GetUserSession() *UserSession {
	if x != nil {
		return x.UserSession
	}
	return nil
}

type PasswordOnboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserHandle    string                 `protobuf:"bytes,1,opt,name=user_handle,json=userHandle,proto3" json:"user_handle,omitempty"`
	NewPassword   []byte                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	DisplayName   *string                `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	DeviceInfo    *Device                `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,proto3,oneof" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordOnboardRequest) Reset() {
	*x = PasswordOnboardRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordOnboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordOnboardRequest) ProtoMessage() {}

func (x *PasswordOnboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordOnboardRequest.ProtoReflect.Descriptor instead.
func (*PasswordOnboardRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *PasswordOnboardRequest) GetUserHandle() string {
	if x != nil {
		return x.UserHandle
	}
	return ""
}

func (x *PasswordOnboardRequest) GetNewPassword() []byte {
	if x != nil {
		return x.NewPassword
	}
	return nil
}

func (x *PasswordOnboardRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *PasswordOnboardRequest) GetDeviceInfo() *Device {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type PasswordOnboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserSession   *UserSession           `protobuf:"bytes,1,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordOnboardResponse) Reset() {
	*x = PasswordOnboardResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordOnboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordOnboardResponse) ProtoMessage() {}

func (x *PasswordOnboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordOnboardResponse.ProtoReflect.Descriptor instead.
func (*PasswordOnboardResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *PasswordOnboardResponse) GetUserSession() *UserSession {
	if x != nil {
		return x.UserSession
	}
	return nil
}

type DiscoverLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nothing       *emptypb.Empty         `protobuf:"bytes,1,opt,name=nothing,proto3" json:"nothing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverLoginRequest) Reset() {
	*x = DiscoverLoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverLoginRequest) ProtoMessage() {}

func (x *DiscoverLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverLoginRequest.ProtoReflect.Descriptor instead.
func (*DiscoverLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoverLoginRequest) GetNothing() *emptypb.Empty {
	if x != nil {
		return x.Nothing
	}
	return nil
}

type DiscoverLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Option        *PublicKeyOption       `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverLoginResponse) Reset() {
	*x = DiscoverLoginResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverLoginResponse) ProtoMessage() {}

func (x *DiscoverLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverLoginResponse.ProtoReflect.Descriptor instead.
func (*DiscoverLoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *DiscoverLoginResponse) GetOption() *PublicKeyOption {
	if x != nil {
		return x.Option
	}
	return nil
}

type VerifyLoginPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *PublicKeyRequest      `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyLoginPublicKeyRequest) Reset() {
	*x = VerifyLoginPublicKeyRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyLoginPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyLoginPublicKeyRequest) ProtoMessage() {}

func (x *VerifyLoginPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyLoginPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*VerifyLoginPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyLoginPublicKeyRequest) GetRequest() *PublicKeyRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type VerifyLoginPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserSession   *UserSession           `protobuf:"bytes,1,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyLoginPublicKeyResponse) Reset() {
	*x = VerifyLoginPublicKeyResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyLoginPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyLoginPublicKeyResponse) ProtoMessage() {}

func (x *VerifyLoginPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyLoginPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*VerifyLoginPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyLoginPublicKeyResponse) GetUserSession() *UserSession {
	if x != nil {
		return x.UserSession
	}
	return nil
}

type PasswordLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserHandle    string                 `protobuf:"bytes,1,opt,name=user_handle,json=userHandle,proto3" json:"user_handle,omitempty"`
	Password      []byte                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	DeviceInfo    *Device                `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo,proto3,oneof" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordLoginRequest) Reset() {
	*x = PasswordLoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordLoginRequest) ProtoMessage() {}

func (x *PasswordLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordLoginRequest.ProtoReflect.Descriptor instead.
func (*PasswordLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *PasswordLoginRequest) GetUserHandle() string {
	if x != nil {
		return x.UserHandle
	}
	return ""
}

func (x *PasswordLoginRequest) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *PasswordLoginRequest) GetDeviceInfo() *Device {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type PasswordLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserSession   *UserSession           `protobuf:"bytes,1,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordLoginResponse) Reset() {
	*x = PasswordLoginResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordLoginResponse) ProtoMessage() {}

func (x *PasswordLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordLoginResponse.ProtoReflect.Descriptor instead.
func (*PasswordLoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *PasswordLoginResponse) GetUserSession() *UserSession {
	if x != nil {
		return x.UserSession
	}
	return nil
}

type Session struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           []byte                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          []byte                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3,oneof" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3,oneof" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *Session) GetAccessToken() []byte {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *Session) GetRefreshToken() []byte {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

func (x *Session) GetAccessTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return nil
}

func (x *Session) GetRefreshTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return nil
}

type RefreshSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionRequest) Reset() {
	*x = RefreshSessionRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionRequest) ProtoMessage() {}

func (x *RefreshSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *RefreshSessionRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type RefreshSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewSession    *Session               `protobuf:"bytes,1,opt,name=new_session,json=newSession,proto3" json:"new_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionResponse) Reset() {
	*x = RefreshSessionResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionResponse) ProtoMessage() {}

func (x *RefreshSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionResponse.ProtoReflect.Descriptor instead.
func (*RefreshSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *RefreshSessionResponse) GetNewSession() *Session {
	if x != nil {
		return x.NewSession
	}
	return nil
}

type ReAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signed        []byte                 `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
	Password      []byte                 `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReAuthRequest) Reset() {
	*x = ReAuthRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReAuthRequest) ProtoMessage() {}

func (x *ReAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReAuthRequest.ProtoReflect.Descriptor instead.
func (*ReAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *ReAuthRequest) GetSigned() []byte {
	if x != nil {
		return x.Signed
	}
	return nil
}

func (x *ReAuthRequest) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type ReAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Option        *PublicKeyOption       `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReAuthResponse) Reset() {
	*x = ReAuthResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReAuthResponse) ProtoMessage() {}

func (x *ReAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReAuthResponse.ProtoReflect.Descriptor instead.
func (*ReAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *ReAuthResponse) GetOption() *PublicKeyOption {
	if x != nil {
		return x.Option
	}
	return nil
}

type VerifyPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signed        []byte                 `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
	UserHandle    *string                `protobuf:"bytes,2,opt,name=user_handle,json=userHandle,proto3,oneof" json:"user_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPublicKeyRequest) Reset() {
	*x = VerifyPublicKeyRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPublicKeyRequest) ProtoMessage() {}

func (x *VerifyPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*VerifyPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{20}
}

func (x *VerifyPublicKeyRequest) GetSigned() []byte {
	if x != nil {
		return x.Signed
	}
	return nil
}

func (x *VerifyPublicKeyRequest) GetUserHandle() string {
	if x != nil && x.UserHandle != nil {
		return *x.UserHandle
	}
	return ""
}

type VerifyPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewSession    *Session               `protobuf:"bytes,1,opt,name=new_session,json=newSession,proto3" json:"new_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPublicKeyResponse) Reset() {
	*x = VerifyPublicKeyResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPublicKeyResponse) ProtoMessage() {}

func (x *VerifyPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*VerifyPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *VerifyPublicKeyResponse) GetNewSession() *Session {
	if x != nil {
		return x.NewSession
	}
	return nil
}

type PasswordReAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserHandle    string                 `protobuf:"bytes,1,opt,name=user_handle,json=userHandle,proto3" json:"user_handle,omitempty"`
	Password      []byte                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordReAuthRequest) Reset() {
	*x = PasswordReAuthRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordReAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordReAuthRequest) ProtoMessage() {}

func (x *PasswordReAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordReAuthRequest.ProtoReflect.Descriptor instead.
func (*PasswordReAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{22}
}

func (x *PasswordReAuthRequest) GetUserHandle() string {
	if x != nil {
		return x.UserHandle
	}
	return ""
}

func (x *PasswordReAuthRequest) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type PasswordReAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewSession    *Session               `protobuf:"bytes,1,opt,name=new_session,json=newSession,proto3" json:"new_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordReAuthResponse) Reset() {
	*x = PasswordReAuthResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordReAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordReAuthResponse) ProtoMessage() {}

func (x *PasswordReAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordReAuthResponse.ProtoReflect.Descriptor instead.
func (*PasswordReAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{23}
}

func (x *PasswordReAuthResponse) GetNewSession() *Session {
	if x != nil {
		return x.NewSession
	}
	return nil
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x16device/v1/device.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12uuid/v1/uuid.proto\"\x94\x01\n" +
	"\x10PublicKeyRequest\x12\x16\n" +
	"\x06signed\x18\x01 \x01(\fR\x06signed\x12$\n" +
	"\vuser_handle\x18\x02 \x01(\tH\x00R\n" +
	"userHandle\x88\x01\x01\x122\n" +
	"\vdevice_info\x18\x03 \x01(\v2\x11.device.v1.DeviceR\n" +
	"deviceInfoB\x0e\n" +
	"\f_user_handle\"l\n" +
	"\x0fPublicKeyOption\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\x12;\n" +
	"\vvalid_until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\"\x98\x04\n" +
	"\vUserSession\x12!\n" +
	"\faccess_token\x18\x01 \x01(\fR\vaccessToken\x12\x1f\n" +
	"\vuser_handle\x18\x02 \x01(\tR\n" +
	"userHandle\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\fR\frefreshToken\x12(\n" +
	"\rtotal_passkey\x18\x05 \x01(\rH\x00R\ftotalPasskey\x88\x01\x01\x12S\n" +
	"\x15last_password_updated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x13lastPasswordUpdated\x88\x01\x01\x12Q\n" +
	"\x17access_token_expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x14accessTokenExpiresAt\x12S\n" +
	"\x18refresh_token_expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x15refreshTokenExpiresAt\x12*\n" +
	"\tdevice_id\x18\t \x01(\v2\r.uuid.v1.UuIdR\bdeviceIdB\x10\n" +
	"\x0e_total_passkeyB\x18\n" +
	"\x16_last_password_updated\"s\n" +
	"\x17PublicKeyOnboardRequest\x12\x1f\n" +
	"\vuser_handle\x18\x01 \x01(\tR\n" +
	"userHandle\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01B\x0f\n" +
	"\r_display_name\"L\n" +
	"\x18PublicKeyOnboardResponse\x120\n" +
	"\x06option\x18\x01 \x01(\v2\x18.auth.v1.PublicKeyOptionR\x06option\"T\n" +
	"\x1dVerifyOnboardPublicKeyRequest\x123\n" +
	"\arequest\x18\x01 \x01(\v2\x19.auth.v1.PublicKeyRequestR\arequest\"Y\n" +
	"\x1eVerifyOnboardPublicKeyResponse\x127\n" +
	"\fuser_session\x18\x01 \x01(\v2\x14.auth.v1.UserSessionR\vuserSession\"\xde\x01\n" +
	"\x16PasswordOnboardRequest\x12\x1f\n" +
	"\vuser_handle\x18\x01 \x01(\tR\n" +
	"userHandle\x12!\n" +
	"\fnew_password\x18\x02 \x01(\fR\vnewPassword\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x127\n" +
	"\vdevice_info\x18\x04 \x01(\v2\x11.device.v1.DeviceH\x01R\n" +
	"deviceInfo\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\x0e\n" +
	"\f_device_info\"R\n" +
	"\x17PasswordOnboardResponse\x127\n" +
	"\fuser_session\x18\x01 \x01(\v2\x14.auth.v1.UserSessionR\vuserSession\"H\n" +
	"\x14DiscoverLoginRequest\x120\n" +
	"\anothing\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\anothing\"I\n" +
	"\x15DiscoverLoginResponse\x120\n" +
	"\x06option\x18\x01 \x01(\v2\x18.auth.v1.PublicKeyOptionR\x06option\"R\n" +
	"\x1bVerifyLoginPublicKeyRequest\x123\n" +
	"\arequest\x18\x01 \x01(\v2\x19.auth.v1.PublicKeyRequestR\arequest\"W\n" +
	"\x1cVerifyLoginPublicKeyResponse\x127\n" +
	"\fuser_session\x18\x01 \x01(\v2\x14.auth.v1.UserSessionR\vuserSession\"\x9c\x01\n" +
	"\x14PasswordLoginRequest\x12\x1f\n" +
	"\vuser_handle\x18\x01 \x01(\tR\n" +
	"userHandle\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\fR\bpassword\x127\n" +
	"\vdevice_info\x18\x03 \x01(\v2\x11.device.v1.DeviceH\x00R\n" +
	"deviceInfo\x88\x01\x01B\x0e\n" +
	"\f_device_info\"P\n" +
	"\x15PasswordLoginResponse\x127\n" +
	"\fuser_session\x18\x01 \x01(\v2\x14.auth.v1.UserSessionR\vuserSession\"\xb2\x02\n" +
	"\aSession\x12!\n" +
	"\faccess_token\x18\x01 \x01(\fR\vaccessToken\x12(\n" +
	"\rrefresh_token\x18\x02 \x01(\fH\x00R\frefreshToken\x88\x01\x01\x12Q\n" +
	"\x17access_token_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x14accessTokenExpiresAt\x12X\n" +
	"\x18refresh_token_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x15refreshTokenExpiresAt\x88\x01\x01B\x10\n" +
	"\x0e_refresh_tokenB\x1b\n" +
	"\x19_refresh_token_expires_at\"-\n" +
	"\x15RefreshSessionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"K\n" +
	"\x16RefreshSessionResponse\x121\n" +
	"\vnew_session\x18\x01 \x01(\v2\x10.auth.v1.SessionR\n" +
	"newSession\"U\n" +
	"\rReAuthRequest\x12\x16\n" +
	"\x06signed\x18\x01 \x01(\fR\x06signed\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\fH\x00R\bpassword\x88\x01\x01B\v\n" +
	"\t_password\"B\n" +
	"\x0eReAuthResponse\x120\n" +
	"\x06option\x18\x01 \x01(\v2\x18.auth.v1.PublicKeyOptionR\x06option\"f\n" +
	"\x16VerifyPublicKeyRequest\x12\x16\n" +
	"\x06signed\x18\x01 \x01(\fR\x06signed\x12$\n" +
	"\vuser_handle\x18\x02 \x01(\tH\x00R\n" +
	"userHandle\x88\x01\x01B\x0e\n" +
	"\f_user_handle\"L\n" +
	"\x17VerifyPublicKeyResponse\x121\n" +
	"\vnew_session\x18\x01 \x01(\v2\x10.auth.v1.SessionR\n" +
	"newSession\"T\n" +
	"\x15PasswordReAuthRequest\x12\x1f\n" +
	"\vuser_handle\x18\x01 \x01(\tR\n" +
	"userHandle\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\fR\bpassword\"K\n" +
	"\x16PasswordReAuthResponse\x121\n" +
	"\vnew_session\x18\x01 \x01(\v2\x10.auth.v1.SessionR\n" +
	"newSession2\xa9\x02\n" +
	"\x0eOnboardService\x12W\n" +
	"\x10PublicKeyOnboard\x12 .auth.v1.PublicKeyOnboardRequest\x1a!.auth.v1.PublicKeyOnboardResponse\x12h\n" +
	"\x16VerifyOnboardPublicKey\x12&.auth.v1.VerifyOnboardPublicKeyRequest\x1a&.auth.v1.VerifyOnboardPublicKeyRequest\x12T\n" +
	"\x0fPasswordOnboard\x12\x1f.auth.v1.PasswordOnboardRequest\x1a .auth.v1.PasswordOnboardResponse2\x92\x02\n" +
	"\vAuthService\x12N\n" +
	"\rDiscoverLogin\x12\x1d.auth.v1.DiscoverLoginRequest\x1a\x1e.auth.v1.DiscoverLoginResponse\x12c\n" +
	"\x14VerifyLoginPublicKey\x12$.auth.v1.VerifyLoginPublicKeyRequest\x1a%.auth.v1.VerifyLoginPublicKeyResponse\x12N\n" +
	"\rPasswordLogin\x12\x1d.auth.v1.PasswordLoginRequest\x1a\x1e.auth.v1.PasswordLoginResponse2\xc6\x02\n" +
	"\rReAuthService\x12Q\n" +
	"\x0eRefreshSession\x12\x1e.auth.v1.RefreshSessionRequest\x1a\x1f.auth.v1.RefreshSessionResponse\x129\n" +
	"\x06ReAuth\x12\x16.auth.v1.ReAuthRequest\x1a\x17.auth.v1.ReAuthResponse\x12T\n" +
	"\x0fVerifyPublicKey\x12\x1f.auth.v1.VerifyPublicKeyRequest\x1a .auth.v1.VerifyPublicKeyResponse\x12Q\n" +
	"\x0ePasswordReAuth\x12\x1e.auth.v1.PasswordReAuthRequest\x1a\x1f.auth.v1.PasswordReAuthResponseB\x06Z\x04./v1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_auth_v1_auth_proto_goTypes = []any{
	(*PublicKeyRequest)(nil),               // 0: auth.v1.PublicKeyRequest
	(*PublicKeyOption)(nil),                // 1: auth.v1.PublicKeyOption
	(*UserSession)(nil),                    // 2: auth.v1.UserSession
	(*PublicKeyOnboardRequest)(nil),        // 3: auth.v1.PublicKeyOnboardRequest
	(*PublicKeyOnboardResponse)(nil),       // 4: auth.v1.PublicKeyOnboardResponse
	(*VerifyOnboardPublicKeyRequest)(nil),  // 5: auth.v1.VerifyOnboardPublicKeyRequest
	(*VerifyOnboardPublicKeyResponse)(nil), // 6: auth.v1.VerifyOnboardPublicKeyResponse
	(*PasswordOnboardRequest)(nil),         // 7: auth.v1.PasswordOnboardRequest
	(*PasswordOnboardResponse)(nil),        // 8: auth.v1.PasswordOnboardResponse
	(*DiscoverLoginRequest)(nil),           // 9: auth.v1.DiscoverLoginRequest
	(*DiscoverLoginResponse)(nil),          // 10: auth.v1.DiscoverLoginResponse
	(*VerifyLoginPublicKeyRequest)(nil),    // 11: auth.v1.VerifyLoginPublicKeyRequest
	(*VerifyLoginPublicKeyResponse)(nil),   // 12: auth.v1.VerifyLoginPublicKeyResponse
	(*PasswordLoginRequest)(nil),           // 13: auth.v1.PasswordLoginRequest
	(*PasswordLoginResponse)(nil),          // 14: auth.v1.PasswordLoginResponse
	(*Session)(nil),                        // 15: auth.v1.Session
	(*RefreshSessionRequest)(nil),          // 16: auth.v1.RefreshSessionRequest
	(*RefreshSessionResponse)(nil),         // 17: auth.v1.RefreshSessionResponse
	(*ReAuthRequest)(nil),                  // 18: auth.v1.ReAuthRequest
	(*ReAuthResponse)(nil),                 // 19: auth.v1.ReAuthResponse
	(*VerifyPublicKeyRequest)(nil),         // 20: auth.v1.VerifyPublicKeyRequest
	(*VerifyPublicKeyResponse)(nil),        // 21: auth.v1.VerifyPublicKeyResponse
	(*PasswordReAuthRequest)(nil),          // 22: auth.v1.PasswordReAuthRequest
	(*PasswordReAuthResponse)(nil),         // 23: auth.v1.PasswordReAuthResponse
	(*Device)(nil),                         // 24: device.v1.Device
	(*timestamppb.Timestamp)(nil),          // 25: google.protobuf.Timestamp
	(*UuId)(nil),                           // 26: uuid.v1.UuId
	(*emptypb.Empty)(nil),                  // 27: google.protobuf.Empty
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	24, // 0: auth.v1.PublicKeyRequest.device_info:type_name -> device.v1.Device
	25, // 1: auth.v1.PublicKeyOption.valid_until:type_name -> google.protobuf.Timestamp
	25, // 2: auth.v1.UserSession.last_password_updated:type_name -> google.protobuf.Timestamp
	25, // 3: auth.v1.UserSession.access_token_expires_at:type_name -> google.protobuf.Timestamp
	25, // 4: auth.v1.UserSession.refresh_token_expires_at:type_name -> google.protobuf.Timestamp
	26, // 5: auth.v1.UserSession.device_id:type_name -> uuid.v1.UuId
	1,  // 6: auth.v1.PublicKeyOnboardResponse.option:type_name -> auth.v1.PublicKeyOption
	0,  // 7: auth.v1.VerifyOnboardPublicKeyRequest.request:type_name -> auth.v1.PublicKeyRequest
	2,  // 8: auth.v1.VerifyOnboardPublicKeyResponse.user_session:type_name -> auth.v1.UserSession
	24, // 9: auth.v1.PasswordOnboardRequest.device_info:type_name -> device.v1.Device
	2,  // 10: auth.v1.PasswordOnboardResponse.user_session:type_name -> auth.v1.UserSession
	27, // 11: auth.v1.DiscoverLoginRequest.nothing:type_name -> google.protobuf.Empty
	1,  // 12: auth.v1.DiscoverLoginResponse.option:type_name -> auth.v1.PublicKeyOption
	0,  // 13: auth.v1.VerifyLoginPublicKeyRequest.request:type_name -> auth.v1.PublicKeyRequest
	2,  // 14: auth.v1.VerifyLoginPublicKeyResponse.user_session:type_name -> auth.v1.UserSession
	24, // 15: auth.v1.PasswordLoginRequest.device_info:type_name -> device.v1.Device
	2,  // 16: auth.v1.PasswordLoginResponse.user_session:type_name -> auth.v1.UserSession
	25, // 17: auth.v1.Session.access_token_expires_at:type_name -> google.protobuf.Timestamp
	25, // 18: auth.v1.Session.refresh_token_expires_at:type_name -> google.protobuf.Timestamp
	15, // 19: auth.v1.RefreshSessionResponse.new_session:type_name -> auth.v1.Session
	1,  // 20: auth.v1.ReAuthResponse.option:type_name -> auth.v1.PublicKeyOption
	15, // 21: auth.v1.VerifyPublicKeyResponse.new_session:type_name -> auth.v1.Session
	15, // 22: auth.v1.PasswordReAuthResponse.new_session:type_name -> auth.v1.Session
	3,  // 23: auth.v1.OnboardService.PublicKeyOnboard:input_type -> auth.v1.PublicKeyOnboardRequest
	5,  // 24: auth.v1.OnboardService.VerifyOnboardPublicKey:input_type -> auth.v1.VerifyOnboardPublicKeyRequest
	7,  // 25: auth.v1.OnboardService.PasswordOnboard:input_type -> auth.v1.PasswordOnboardRequest
	9,  // 26: auth.v1.AuthService.DiscoverLogin:input_type -> auth.v1.DiscoverLoginRequest
	11, // 27: auth.v1.AuthService.VerifyLoginPublicKey:input_type -> auth.v1.VerifyLoginPublicKeyRequest
	13, // 28: auth.v1.AuthService.PasswordLogin:input_type -> auth.v1.PasswordLoginRequest
	16, // 29: auth.v1.ReAuthService.RefreshSession:input_type -> auth.v1.RefreshSessionRequest
	18, // 30: auth.v1.ReAuthService.ReAuth:input_type -> auth.v1.ReAuthRequest
	20, // 31: auth.v1.ReAuthService.VerifyPublicKey:input_type -> auth.v1.VerifyPublicKeyRequest
	22, // 32: auth.v1.ReAuthService.PasswordReAuth:input_type -> auth.v1.PasswordReAuthRequest
	4,  // 33: auth.v1.OnboardService.PublicKeyOnboard:output_type -> auth.v1.PublicKeyOnboardResponse
	5,  // 34: auth.v1.OnboardService.VerifyOnboardPublicKey:output_type -> auth.v1.VerifyOnboardPublicKeyRequest
	8,  // 35: auth.v1.OnboardService.PasswordOnboard:output_type -> auth.v1.PasswordOnboardResponse
	10, // 36: auth.v1.AuthService.DiscoverLogin:output_type -> auth.v1.DiscoverLoginResponse
	12, // 37: auth.v1.AuthService.VerifyLoginPublicKey:output_type -> auth.v1.VerifyLoginPublicKeyResponse
	14, // 38: auth.v1.AuthService.PasswordLogin:output_type -> auth.v1.PasswordLoginResponse
	17, // 39: auth.v1.ReAuthService.RefreshSession:output_type -> auth.v1.RefreshSessionResponse
	19, // 40: auth.v1.ReAuthService.ReAuth:output_type -> auth.v1.ReAuthResponse
	21, // 41: auth.v1.ReAuthService.VerifyPublicKey:output_type -> auth.v1.VerifyPublicKeyResponse
	23, // 42: auth.v1.ReAuthService.PasswordReAuth:output_type -> auth.v1.PasswordReAuthResponse
	33, // [33:43] is the sub-list for method output_type
	23, // [23:33] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	file_device_v1_device_proto_init()
	file_uuid_v1_uuid_proto_init()
	file_auth_v1_auth_proto_msgTypes[0].OneofWrappers = []any{}
	file_auth_v1_auth_proto_msgTypes[2].OneofWrappers = []any{}
	file_auth_v1_auth_proto_msgTypes[3].OneofWrappers = []any{}
	file_auth_v1_auth_proto_msgTypes[7].OneofWrappers = []any{}
	file_auth_v1_auth_proto_msgTypes[13].OneofWrappers = []any{}
	file_auth_v1_auth_proto_msgTypes[15].OneofWrappers = []any{}
	file_auth_v1_auth_proto_msgTypes[18].OneofWrappers = []any{}
	file_auth_v1_auth_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
