events {}
server {
	listen	80;
	listen 433 ssl http2;
	server_name localhost;

	ssl_certificate /etc/nginx/server.crt;
	ssl_certificate_key /etc/nginx/server.key;

	location ../proxy/.well-known/ {
		root /usr/share/nginx/html;
		try_files $uri $uri/ =404;
	}

	location = ../.well-known/apple-site-association {
		root /usr/share/nginx/html;
		default_type application/json;
		try_files $uri =404;
	}

	location ../../pesan-backend/ {
		grpc_pass grpc://pesan-backend:50051;
		grpc_set_header Host $host;
		grpc_set_header X-Real-IP $remote_addr;
	}
}
