// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: shop/v1/shop.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactType int32

const (
	ContactType_email ContactType = 0
	ContactType_phone ContactType = 1
)

// Enum value maps for ContactType.
var (
	ContactType_name = map[int32]string{
		0: "email",
		1: "phone",
	}
	ContactType_value = map[string]int32{
		"email": 0,
		"phone": 1,
	}
)

func (x ContactType) Enum() *ContactType {
	p := new(ContactType)
	*p = x
	return p
}

func (x ContactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContactType) Descriptor() protoreflect.EnumDescriptor {
	return file_shop_v1_shop_proto_enumTypes[0].Descriptor()
}

func (ContactType) Type() protoreflect.EnumType {
	return &file_shop_v1_shop_proto_enumTypes[0]
}

func (x ContactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContactType.Descriptor instead.
func (ContactType) EnumDescriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{0}
}

type Day int32

const (
	Day_monday    Day = 0
	Day_tuesday   Day = 1
	Day_wednesday Day = 2
	Day_thursday  Day = 3
	Day_friday    Day = 4
	Day_saturday  Day = 5
	Day_sunday    Day = 6
)

// Enum value maps for Day.
var (
	Day_name = map[int32]string{
		0: "monday",
		1: "tuesday",
		2: "wednesday",
		3: "thursday",
		4: "friday",
		5: "saturday",
		6: "sunday",
	}
	Day_value = map[string]int32{
		"monday":    0,
		"tuesday":   1,
		"wednesday": 2,
		"thursday":  3,
		"friday":    4,
		"saturday":  5,
		"sunday":    6,
	}
)

func (x Day) Enum() *Day {
	p := new(Day)
	*p = x
	return p
}

func (x Day) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Day) Descriptor() protoreflect.EnumDescriptor {
	return file_shop_v1_shop_proto_enumTypes[1].Descriptor()
}

func (Day) Type() protoreflect.EnumType {
	return &file_shop_v1_shop_proto_enumTypes[1]
}

func (x Day) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Day.Descriptor instead.
func (Day) EnumDescriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{1}
}

type ShopDeviceStatus int32

const (
	ShopDeviceStatus_online  ShopDeviceStatus = 0
	ShopDeviceStatus_offline ShopDeviceStatus = 1
)

// Enum value maps for ShopDeviceStatus.
var (
	ShopDeviceStatus_name = map[int32]string{
		0: "online",
		1: "offline",
	}
	ShopDeviceStatus_value = map[string]int32{
		"online":  0,
		"offline": 1,
	}
)

func (x ShopDeviceStatus) Enum() *ShopDeviceStatus {
	p := new(ShopDeviceStatus)
	*p = x
	return p
}

func (x ShopDeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShopDeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shop_v1_shop_proto_enumTypes[2].Descriptor()
}

func (ShopDeviceStatus) Type() protoreflect.EnumType {
	return &file_shop_v1_shop_proto_enumTypes[2]
}

func (x ShopDeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShopDeviceStatus.Descriptor instead.
func (ShopDeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{2}
}

type ServingMethod int32

const (
	ServingMethod_dine_in   ServingMethod = 0
	ServingMethod_take_away ServingMethod = 1
	ServingMethod_delivery  ServingMethod = 2
)

// Enum value maps for ServingMethod.
var (
	ServingMethod_name = map[int32]string{
		0: "dine_in",
		1: "take_away",
		2: "delivery",
	}
	ServingMethod_value = map[string]int32{
		"dine_in":   0,
		"take_away": 1,
		"delivery":  2,
	}
)

func (x ServingMethod) Enum() *ServingMethod {
	p := new(ServingMethod)
	*p = x
	return p
}

func (x ServingMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServingMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_shop_v1_shop_proto_enumTypes[3].Descriptor()
}

func (ServingMethod) Type() protoreflect.EnumType {
	return &file_shop_v1_shop_proto_enumTypes[3]
}

func (x ServingMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServingMethod.Descriptor instead.
func (ServingMethod) EnumDescriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{3}
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ContactType            `protobuf:"varint,1,opt,name=type,proto3,enum=shop.v1.ContactType" json:"type,omitempty"`
	Display       string                 `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	Actual        string                 `protobuf:"bytes,3,opt,name=actual,proto3" json:"actual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_shop_v1_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{0}
}

func (x *Contact) GetType() ContactType {
	if x != nil {
		return x.Type
	}
	return ContactType_email
}

func (x *Contact) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *Contact) GetActual() string {
	if x != nil {
		return x.Actual
	}
	return ""
}

type OperationHour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          int32                  `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute        int32                  `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationHour) Reset() {
	*x = OperationHour{}
	mi := &file_shop_v1_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationHour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationHour) ProtoMessage() {}

func (x *OperationHour) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationHour.ProtoReflect.Descriptor instead.
func (*OperationHour) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{1}
}

func (x *OperationHour) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *OperationHour) GetMinute() int32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

type CreateNewShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Contacts      []*Contact             `protobuf:"bytes,2,rep,name=contacts,proto3" json:"contacts,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	OpensAt       *OperationHour         `protobuf:"bytes,5,opt,name=opens_at,json=opensAt,proto3" json:"opens_at,omitempty"`
	ClosesAt      *OperationHour         `protobuf:"bytes,6,opt,name=closes_at,json=closesAt,proto3" json:"closes_at,omitempty"`
	OperationDays []Day                  `protobuf:"varint,7,rep,packed,name=operation_days,json=operationDays,proto3,enum=shop.v1.Day" json:"operation_days,omitempty"`
	// this is to allow the refresh process efficiently
	RefreshToken  []byte         `protobuf:"bytes,8,opt,name=refresh_token,json=refreshToken,proto3,oneof" json:"refresh_token,omitempty"`
	RAuth         *ReAuthRequest `protobuf:"bytes,9,opt,name=r_auth,json=rAuth,proto3,oneof" json:"r_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewShopRequest) Reset() {
	*x = CreateNewShopRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewShopRequest) ProtoMessage() {}

func (x *CreateNewShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewShopRequest.ProtoReflect.Descriptor instead.
func (*CreateNewShopRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNewShopRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNewShopRequest) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *CreateNewShopRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateNewShopRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateNewShopRequest) GetOpensAt() *OperationHour {
	if x != nil {
		return x.OpensAt
	}
	return nil
}

func (x *CreateNewShopRequest) GetClosesAt() *OperationHour {
	if x != nil {
		return x.ClosesAt
	}
	return nil
}

func (x *CreateNewShopRequest) GetOperationDays() []Day {
	if x != nil {
		return x.OperationDays
	}
	return nil
}

func (x *CreateNewShopRequest) GetRefreshToken() []byte {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

func (x *CreateNewShopRequest) GetRAuth() *ReAuthRequest {
	if x != nil {
		return x.RAuth
	}
	return nil
}

type CreateNewShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        *UuId                  `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	LastUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	FreshSession  *Session               `protobuf:"bytes,3,opt,name=fresh_session,json=freshSession,proto3,oneof" json:"fresh_session,omitempty"`
	Options       *PublicKeyOption       `protobuf:"bytes,4,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewShopResponse) Reset() {
	*x = CreateNewShopResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewShopResponse) ProtoMessage() {}

func (x *CreateNewShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewShopResponse.ProtoReflect.Descriptor instead.
func (*CreateNewShopResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNewShopResponse) GetShopId() *UuId {
	if x != nil {
		return x.ShopId
	}
	return nil
}

func (x *CreateNewShopResponse) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

func (x *CreateNewShopResponse) GetFreshSession() *Session {
	if x != nil {
		return x.FreshSession
	}
	return nil
}

func (x *CreateNewShopResponse) GetOptions() *PublicKeyOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetShopsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Page            uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	LastRequestedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_requested_at,json=lastRequestedAt,proto3" json:"last_requested_at,omitempty"`
	// this is to allow the refresh process efficiently
	RefreshToken  []byte         `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3,oneof" json:"refresh_token,omitempty"`
	RAuth         *ReAuthRequest `protobuf:"bytes,4,opt,name=r_auth,json=rAuth,proto3,oneof" json:"r_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopsRequest) Reset() {
	*x = GetShopsRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopsRequest) ProtoMessage() {}

func (x *GetShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopsRequest.ProtoReflect.Descriptor instead.
func (*GetShopsRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{4}
}

func (x *GetShopsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetShopsRequest) GetLastRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRequestedAt
	}
	return nil
}

func (x *GetShopsRequest) GetRefreshToken() []byte {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

func (x *GetShopsRequest) GetRAuth() *ReAuthRequest {
	if x != nil {
		return x.RAuth
	}
	return nil
}

type ShopPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        *UuId                  `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	OpensAt       *OperationHour         `protobuf:"bytes,4,opt,name=opens_at,json=opensAt,proto3" json:"opens_at,omitempty"`
	ClosesAt      *OperationHour         `protobuf:"bytes,5,opt,name=closes_at,json=closesAt,proto3" json:"closes_at,omitempty"`
	Contacts      []*Contact             `protobuf:"bytes,6,rep,name=contacts,proto3" json:"contacts,omitempty"`
	OperationDays []Day                  `protobuf:"varint,7,rep,packed,name=operation_days,json=operationDays,proto3,enum=shop.v1.Day" json:"operation_days,omitempty"`
	Location      *string                `protobuf:"bytes,8,opt,name=location,proto3,oneof" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopPb) Reset() {
	*x = ShopPb{}
	mi := &file_shop_v1_shop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopPb) ProtoMessage() {}

func (x *ShopPb) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopPb.ProtoReflect.Descriptor instead.
func (*ShopPb) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{5}
}

func (x *ShopPb) GetShopId() *UuId {
	if x != nil {
		return x.ShopId
	}
	return nil
}

func (x *ShopPb) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopPb) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ShopPb) GetOpensAt() *OperationHour {
	if x != nil {
		return x.OpensAt
	}
	return nil
}

func (x *ShopPb) GetClosesAt() *OperationHour {
	if x != nil {
		return x.ClosesAt
	}
	return nil
}

func (x *ShopPb) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *ShopPb) GetOperationDays() []Day {
	if x != nil {
		return x.OperationDays
	}
	return nil
}

func (x *ShopPb) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

type RolePb struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoleId         *UuId                  `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	EditShop       bool                   `protobuf:"varint,2,opt,name=edit_shop,json=editShop,proto3" json:"edit_shop,omitempty"`
	OpenCloseShop  bool                   `protobuf:"varint,3,opt,name=open_close_shop,json=openCloseShop,proto3" json:"open_close_shop,omitempty"`
	CreateProducts bool                   `protobuf:"varint,4,opt,name=create_products,json=createProducts,proto3" json:"create_products,omitempty"`
	EditProducts   bool                   `protobuf:"varint,5,opt,name=edit_products,json=editProducts,proto3" json:"edit_products,omitempty"`
	DeleteProducts bool                   `protobuf:"varint,6,opt,name=delete_products,json=deleteProducts,proto3" json:"delete_products,omitempty"`
	CreateOrders   bool                   `protobuf:"varint,7,opt,name=create_orders,json=createOrders,proto3" json:"create_orders,omitempty"`
	EditOrders     bool                   `protobuf:"varint,8,opt,name=edit_orders,json=editOrders,proto3" json:"edit_orders,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RolePb) Reset() {
	*x = RolePb{}
	mi := &file_shop_v1_shop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePb) ProtoMessage() {}

func (x *RolePb) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePb.ProtoReflect.Descriptor instead.
func (*RolePb) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{6}
}

func (x *RolePb) GetRoleId() *UuId {
	if x != nil {
		return x.RoleId
	}
	return nil
}

func (x *RolePb) GetEditShop() bool {
	if x != nil {
		return x.EditShop
	}
	return false
}

func (x *RolePb) GetOpenCloseShop() bool {
	if x != nil {
		return x.OpenCloseShop
	}
	return false
}

func (x *RolePb) GetCreateProducts() bool {
	if x != nil {
		return x.CreateProducts
	}
	return false
}

func (x *RolePb) GetEditProducts() bool {
	if x != nil {
		return x.EditProducts
	}
	return false
}

func (x *RolePb) GetDeleteProducts() bool {
	if x != nil {
		return x.DeleteProducts
	}
	return false
}

func (x *RolePb) GetCreateOrders() bool {
	if x != nil {
		return x.CreateOrders
	}
	return false
}

func (x *RolePb) GetEditOrders() bool {
	if x != nil {
		return x.EditOrders
	}
	return false
}

type ShopRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *ShopPb                `protobuf:"bytes,1,opt,name=shop,proto3,oneof" json:"shop,omitempty"`
	Role          *RolePb                `protobuf:"bytes,2,opt,name=role,proto3,oneof" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopRole) Reset() {
	*x = ShopRole{}
	mi := &file_shop_v1_shop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopRole) ProtoMessage() {}

func (x *ShopRole) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopRole.ProtoReflect.Descriptor instead.
func (*ShopRole) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{7}
}

func (x *ShopRole) GetShop() *ShopPb {
	if x != nil {
		return x.Shop
	}
	return nil
}

func (x *ShopRole) GetRole() *RolePb {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetShopsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shops         []*ShopRole            `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	FreshSession  *Session               `protobuf:"bytes,2,opt,name=fresh_session,json=freshSession,proto3,oneof" json:"fresh_session,omitempty"`
	Options       *PublicKeyOption       `protobuf:"bytes,3,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopsResponse) Reset() {
	*x = GetShopsResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopsResponse) ProtoMessage() {}

func (x *GetShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopsResponse.ProtoReflect.Descriptor instead.
func (*GetShopsResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{8}
}

func (x *GetShopsResponse) GetShops() []*ShopRole {
	if x != nil {
		return x.Shops
	}
	return nil
}

func (x *GetShopsResponse) GetFreshSession() *Session {
	if x != nil {
		return x.FreshSession
	}
	return nil
}

func (x *GetShopsResponse) GetOptions() *PublicKeyOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type ShopDeviceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        *UuId                  `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	DeviceId      *UuId                  `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopDeviceStatusRequest) Reset() {
	*x = ShopDeviceStatusRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopDeviceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopDeviceStatusRequest) ProtoMessage() {}

func (x *ShopDeviceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopDeviceStatusRequest.ProtoReflect.Descriptor instead.
func (*ShopDeviceStatusRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{9}
}

func (x *ShopDeviceStatusRequest) GetShopId() *UuId {
	if x != nil {
		return x.ShopId
	}
	return nil
}

func (x *ShopDeviceStatusRequest) GetDeviceId() *UuId {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

type ShopDeviceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ShopDeviceStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=shop.v1.ShopDeviceStatus" json:"status,omitempty"`
	TotalConsumer int32                  `protobuf:"varint,2,opt,name=total_consumer,json=totalConsumer,proto3" json:"total_consumer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopDeviceStatusResponse) Reset() {
	*x = ShopDeviceStatusResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopDeviceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopDeviceStatusResponse) ProtoMessage() {}

func (x *ShopDeviceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopDeviceStatusResponse.ProtoReflect.Descriptor instead.
func (*ShopDeviceStatusResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{10}
}

func (x *ShopDeviceStatusResponse) GetStatus() ShopDeviceStatus {
	if x != nil {
		return x.Status
	}
	return ShopDeviceStatus_online
}

func (x *ShopDeviceStatusResponse) GetTotalConsumer() int32 {
	if x != nil {
		return x.TotalConsumer
	}
	return 0
}

type OpenShopRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ShopId            *UuId                  `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	OpenUntil         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=open_until,json=openUntil,proto3" json:"open_until,omitempty"`
	UpdateClosingTime *bool                  `protobuf:"varint,3,opt,name=update_closing_time,json=updateClosingTime,proto3,oneof" json:"update_closing_time,omitempty"`
	// NOTE: [INFO] merchant needs to provide their nkey(public) for the first 'open for business'
	O4BPk         []byte `protobuf:"bytes,4,opt,name=o4b_pk,json=o4bPk,proto3,oneof" json:"o4b_pk,omitempty"`
	DeviceId      *UuId  `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenShopRequest) Reset() {
	*x = OpenShopRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenShopRequest) ProtoMessage() {}

func (x *OpenShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenShopRequest.ProtoReflect.Descriptor instead.
func (*OpenShopRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{11}
}

func (x *OpenShopRequest) GetShopId() *UuId {
	if x != nil {
		return x.ShopId
	}
	return nil
}

func (x *OpenShopRequest) GetOpenUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenUntil
	}
	return nil
}

func (x *OpenShopRequest) GetUpdateClosingTime() bool {
	if x != nil && x.UpdateClosingTime != nil {
		return *x.UpdateClosingTime
	}
	return false
}

func (x *OpenShopRequest) GetO4BPk() []byte {
	if x != nil {
		return x.O4BPk
	}
	return nil
}

func (x *OpenShopRequest) GetDeviceId() *UuId {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

type OpenShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            *emptypb.Empty         `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenShopResponse) Reset() {
	*x = OpenShopResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenShopResponse) ProtoMessage() {}

func (x *OpenShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenShopResponse.ProtoReflect.Descriptor instead.
func (*OpenShopResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{12}
}

func (x *OpenShopResponse) GetOk() *emptypb.Empty {
	if x != nil {
		return x.Ok
	}
	return nil
}

type CloseShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        *UuId                  `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseShopRequest) Reset() {
	*x = CloseShopRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseShopRequest) ProtoMessage() {}

func (x *CloseShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseShopRequest.ProtoReflect.Descriptor instead.
func (*CloseShopRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{13}
}

func (x *CloseShopRequest) GetShopId() *UuId {
	if x != nil {
		return x.ShopId
	}
	return nil
}

type CloseShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            *emptypb.Empty         `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseShopResponse) Reset() {
	*x = CloseShopResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseShopResponse) ProtoMessage() {}

func (x *CloseShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseShopResponse.ProtoReflect.Descriptor instead.
func (*CloseShopResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{14}
}

func (x *CloseShopResponse) GetOk() *emptypb.Empty {
	if x != nil {
		return x.Ok
	}
	return nil
}

// server needs to keep this data; easier to generate session for customer app
type UpdateOrderAccessConfigRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OrderSessionDuration *int64                 `protobuf:"varint,1,opt,name=order_session_duration,json=orderSessionDuration,proto3,oneof" json:"order_session_duration,omitempty"`     // default is 10 minutes, for customer to place orders
	RequiresAdditionalId *bool                  `protobuf:"varint,2,opt,name=requires_additional_id,json=requiresAdditionalId,proto3,oneof" json:"requires_additional_id,omitempty"`     // mobile no. or table no., customer needs to provide this in order to place an order
	ServingMethod        *ServingMethod         `protobuf:"varint,3,opt,name=serving_method,json=servingMethod,proto3,enum=shop.v1.ServingMethod,oneof" json:"serving_method,omitempty"` // dine and take-away; delivery maybe in future
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateOrderAccessConfigRequest) Reset() {
	*x = UpdateOrderAccessConfigRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderAccessConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderAccessConfigRequest) ProtoMessage() {}

func (x *UpdateOrderAccessConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderAccessConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderAccessConfigRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateOrderAccessConfigRequest) GetOrderSessionDuration() int64 {
	if x != nil && x.OrderSessionDuration != nil {
		return *x.OrderSessionDuration
	}
	return 0
}

func (x *UpdateOrderAccessConfigRequest) GetRequiresAdditionalId() bool {
	if x != nil && x.RequiresAdditionalId != nil {
		return *x.RequiresAdditionalId
	}
	return false
}

func (x *UpdateOrderAccessConfigRequest) GetServingMethod() ServingMethod {
	if x != nil && x.ServingMethod != nil {
		return *x.ServingMethod
	}
	return ServingMethod_dine_in
}

type UpdateOrderAccessConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            *emptypb.Empty         `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderAccessConfigResponse) Reset() {
	*x = UpdateOrderAccessConfigResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderAccessConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderAccessConfigResponse) ProtoMessage() {}

func (x *UpdateOrderAccessConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderAccessConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderAccessConfigResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateOrderAccessConfigResponse) GetOk() *emptypb.Empty {
	if x != nil {
		return x.Ok
	}
	return nil
}

type Category struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// for existing category selection
	CategoryId *string `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	// for new category
	Name            *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description     *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	AvailableFrom   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=available_from,json=availableFrom,proto3,oneof" json:"available_from,omitempty"`
	AvailableUntil  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=available_until,json=availableUntil,proto3,oneof" json:"available_until,omitempty"`
	AvailableWeekly []string               `protobuf:"bytes,6,rep,name=available_weekly,json=availableWeekly,proto3" json:"available_weekly,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_shop_v1_shop_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{17}
}

func (x *Category) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Category) GetAvailableFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.AvailableFrom
	}
	return nil
}

func (x *Category) GetAvailableUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.AvailableUntil
	}
	return nil
}

func (x *Category) GetAvailableWeekly() []string {
	if x != nil {
		return x.AvailableWeekly
	}
	return nil
}

type CreateNewProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	UnitLabel     string                 `protobuf:"bytes,3,opt,name=unit_label,json=unitLabel,proto3" json:"unit_label,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Categories    []*Category            `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewProductRequest) Reset() {
	*x = CreateNewProductRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewProductRequest) ProtoMessage() {}

func (x *CreateNewProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewProductRequest.ProtoReflect.Descriptor instead.
func (*CreateNewProductRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{18}
}

func (x *CreateNewProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNewProductRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateNewProductRequest) GetUnitLabel() string {
	if x != nil {
		return x.UnitLabel
	}
	return ""
}

func (x *CreateNewProductRequest) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *CreateNewProductRequest) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateNewProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewProductId  string                 `protobuf:"bytes,1,opt,name=new_product_id,json=newProductId,proto3" json:"new_product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewProductResponse) Reset() {
	*x = CreateNewProductResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewProductResponse) ProtoMessage() {}

func (x *CreateNewProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewProductResponse.ProtoReflect.Descriptor instead.
func (*CreateNewProductResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{19}
}

func (x *CreateNewProductResponse) GetNewProductId() string {
	if x != nil {
		return x.NewProductId
	}
	return ""
}

type NewPhoto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPhoto) Reset() {
	*x = NewPhoto{}
	mi := &file_shop_v1_shop_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPhoto) ProtoMessage() {}

func (x *NewPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPhoto.ProtoReflect.Descriptor instead.
func (*NewPhoto) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{20}
}

func (x *NewPhoto) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type OrderSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        *UuId                  `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSessionRequest) Reset() {
	*x = OrderSessionRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSessionRequest) ProtoMessage() {}

func (x *OrderSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSessionRequest.ProtoReflect.Descriptor instead.
func (*OrderSessionRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{21}
}

func (x *OrderSessionRequest) GetShopId() *UuId {
	if x != nil {
		return x.ShopId
	}
	return nil
}

type OrderSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSubject  string                 `protobuf:"bytes,1,opt,name=order_subject,json=orderSubject,proto3" json:"order_subject,omitempty"`
	OrderToken    string                 `protobuf:"bytes,2,opt,name=order_token,json=orderToken,proto3" json:"order_token,omitempty"` // customer gateway to the nats stream
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSession) Reset() {
	*x = OrderSession{}
	mi := &file_shop_v1_shop_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSession) ProtoMessage() {}

func (x *OrderSession) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSession.ProtoReflect.Descriptor instead.
func (*OrderSession) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{22}
}

func (x *OrderSession) GetOrderSubject() string {
	if x != nil {
		return x.OrderSubject
	}
	return ""
}

func (x *OrderSession) GetOrderToken() string {
	if x != nil {
		return x.OrderToken
	}
	return ""
}

func (x *OrderSession) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_shop_v1_shop_proto protoreflect.FileDescriptor

const file_shop_v1_shop_proto_rawDesc = "" +
	"\n" +
	"\x12shop/v1/shop.proto\x12\ashop.v1\x1a\x12auth/v1/auth.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12uuid/v1/uuid.proto\"e\n" +
	"\aContact\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.shop.v1.ContactTypeR\x04type\x12\x18\n" +
	"\adisplay\x18\x02 \x01(\tR\adisplay\x12\x16\n" +
	"\x06actual\x18\x03 \x01(\tR\x06actual\";\n" +
	"\rOperationHour\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\x05R\x04hour\x12\x16\n" +
	"\x06minute\x18\x02 \x01(\x05R\x06minute\"\xa0\x03\n" +
	"\x14CreateNewShopRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\bcontacts\x18\x02 \x03(\v2\x10.shop.v1.ContactR\bcontacts\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x121\n" +
	"\bopens_at\x18\x05 \x01(\v2\x16.shop.v1.OperationHourR\aopensAt\x123\n" +
	"\tcloses_at\x18\x06 \x01(\v2\x16.shop.v1.OperationHourR\bclosesAt\x123\n" +
	"\x0eoperation_days\x18\a \x03(\x0e2\f.shop.v1.DayR\roperationDays\x12(\n" +
	"\rrefresh_token\x18\b \x01(\fH\x00R\frefreshToken\x88\x01\x01\x122\n" +
	"\x06r_auth\x18\t \x01(\v2\x16.auth.v1.ReAuthRequestH\x01R\x05rAuth\x88\x01\x01B\x10\n" +
	"\x0e_refresh_tokenB\t\n" +
	"\a_r_auth\"\x96\x02\n" +
	"\x15CreateNewShopResponse\x12&\n" +
	"\ashop_id\x18\x01 \x01(\v2\r.uuid.v1.UuIdR\x06shopId\x12B\n" +
	"\x0flast_updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rlastUpdatedAt\x12:\n" +
	"\rfresh_session\x18\x03 \x01(\v2\x10.auth.v1.SessionH\x00R\ffreshSession\x88\x01\x01\x127\n" +
	"\aoptions\x18\x04 \x01(\v2\x18.auth.v1.PublicKeyOptionH\x01R\aoptions\x88\x01\x01B\x10\n" +
	"\x0e_fresh_sessionB\n" +
	"\n" +
	"\b_options\"\xe8\x01\n" +
	"\x0fGetShopsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12F\n" +
	"\x11last_requested_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastRequestedAt\x12(\n" +
	"\rrefresh_token\x18\x03 \x01(\fH\x00R\frefreshToken\x88\x01\x01\x122\n" +
	"\x06r_auth\x18\x04 \x01(\v2\x16.auth.v1.ReAuthRequestH\x01R\x05rAuth\x88\x01\x01B\x10\n" +
	"\x0e_refresh_tokenB\t\n" +
	"\a_r_auth\"\xd1\x02\n" +
	"\x06ShopPb\x12&\n" +
	"\ashop_id\x18\x01 \x01(\v2\r.uuid.v1.UuIdR\x06shopId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x121\n" +
	"\bopens_at\x18\x04 \x01(\v2\x16.shop.v1.OperationHourR\aopensAt\x123\n" +
	"\tcloses_at\x18\x05 \x01(\v2\x16.shop.v1.OperationHourR\bclosesAt\x12,\n" +
	"\bcontacts\x18\x06 \x03(\v2\x10.shop.v1.ContactR\bcontacts\x123\n" +
	"\x0eoperation_days\x18\a \x03(\x0e2\f.shop.v1.DayR\roperationDays\x12\x1f\n" +
	"\blocation\x18\b \x01(\tH\x00R\blocation\x88\x01\x01B\v\n" +
	"\t_location\"\xb2\x02\n" +
	"\x06RolePb\x12&\n" +
	"\arole_id\x18\x01 \x01(\v2\r.uuid.v1.UuIdR\x06roleId\x12\x1b\n" +
	"\tedit_shop\x18\x02 \x01(\bR\beditShop\x12&\n" +
	"\x0fopen_close_shop\x18\x03 \x01(\bR\ropenCloseShop\x12'\n" +
	"\x0fcreate_products\x18\x04 \x01(\bR\x0ecreateProducts\x12#\n" +
	"\redit_products\x18\x05 \x01(\bR\feditProducts\x12'\n" +
	"\x0fdelete_products\x18\x06 \x01(\bR\x0edeleteProducts\x12#\n" +
	"\rcreate_orders\x18\a \x01(\bR\fcreateOrders\x12\x1f\n" +
	"\vedit_orders\x18\b \x01(\bR\n" +
	"editOrders\"p\n" +
	"\bShopRole\x12(\n" +
	"\x04shop\x18\x01 \x01(\v2\x0f.shop.v1.ShopPbH\x00R\x04shop\x88\x01\x01\x12(\n" +
	"\x04role\x18\x02 \x01(\v2\x0f.shop.v1.RolePbH\x01R\x04role\x88\x01\x01B\a\n" +
	"\x05_shopB\a\n" +
	"\x05_role\"\xce\x01\n" +
	"\x10GetShopsResponse\x12'\n" +
	"\x05shops\x18\x01 \x03(\v2\x11.shop.v1.ShopRoleR\x05shops\x12:\n" +
	"\rfresh_session\x18\x02 \x01(\v2\x10.auth.v1.SessionH\x00R\ffreshSession\x88\x01\x01\x127\n" +
	"\aoptions\x18\x03 \x01(\v2\x18.auth.v1.PublicKeyOptionH\x01R\aoptions\x88\x01\x01B\x10\n" +
	"\x0e_fresh_sessionB\n" +
	"\n" +
	"\b_options\"m\n" +
	"\x17ShopDeviceStatusRequest\x12&\n" +
	"\ashop_id\x18\x01 \x01(\v2\r.uuid.v1.UuIdR\x06shopId\x12*\n" +
	"\tdevice_id\x18\x02 \x01(\v2\r.uuid.v1.UuIdR\bdeviceId\"t\n" +
	"\x18ShopDeviceStatusResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.shop.v1.ShopDeviceStatusR\x06status\x12%\n" +
	"\x0etotal_consumer\x18\x02 \x01(\x05R\rtotalConsumer\"\x94\x02\n" +
	"\x0fOpenShopRequest\x12&\n" +
	"\ashop_id\x18\x01 \x01(\v2\r.uuid.v1.UuIdR\x06shopId\x129\n" +
	"\n" +
	"open_until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\topenUntil\x123\n" +
	"\x13update_closing_time\x18\x03 \x01(\bH\x00R\x11updateClosingTime\x88\x01\x01\x12\x1a\n" +
	"\x06o4b_pk\x18\x04 \x01(\fH\x01R\x05o4bPk\x88\x01\x01\x12*\n" +
	"\tdevice_id\x18\x05 \x01(\v2\r.uuid.v1.UuIdR\bdeviceIdB\x16\n" +
	"\x14_update_closing_timeB\t\n" +
	"\a_o4b_pk\":\n" +
	"\x10OpenShopResponse\x12&\n" +
	"\x02ok\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x02ok\":\n" +
	"\x10CloseShopRequest\x12&\n" +
	"\ashop_id\x18\x01 \x01(\v2\r.uuid.v1.UuIdR\x06shopId\";\n" +
	"\x11CloseShopResponse\x12&\n" +
	"\x02ok\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x02ok\"\xa3\x02\n" +
	"\x1eUpdateOrderAccessConfigRequest\x129\n" +
	"\x16order_session_duration\x18\x01 \x01(\x03H\x00R\x14orderSessionDuration\x88\x01\x01\x129\n" +
	"\x16requires_additional_id\x18\x02 \x01(\bH\x01R\x14requiresAdditionalId\x88\x01\x01\x12B\n" +
	"\x0eserving_method\x18\x03 \x01(\x0e2\x16.shop.v1.ServingMethodH\x02R\rservingMethod\x88\x01\x01B\x19\n" +
	"\x17_order_session_durationB\x19\n" +
	"\x17_requires_additional_idB\x11\n" +
	"\x0f_serving_method\"I\n" +
	"\x1fUpdateOrderAccessConfigResponse\x12&\n" +
	"\x02ok\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x02ok\"\xfd\x02\n" +
	"\bCategory\x12$\n" +
	"\vcategory_id\x18\x01 \x01(\tH\x00R\n" +
	"categoryId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x02R\vdescription\x88\x01\x01\x12F\n" +
	"\x0eavailable_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\ravailableFrom\x88\x01\x01\x12H\n" +
	"\x0favailable_until\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x0eavailableUntil\x88\x01\x01\x12)\n" +
	"\x10available_weekly\x18\x06 \x03(\tR\x0favailableWeeklyB\x0e\n" +
	"\f_category_idB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_available_fromB\x12\n" +
	"\x10_available_until\"\xd5\x01\n" +
	"\x17CreateNewProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"unit_label\x18\x03 \x01(\tR\tunitLabel\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\x121\n" +
	"\n" +
	"categories\x18\x05 \x03(\v2\x11.shop.v1.CategoryR\n" +
	"categoriesB\x0e\n" +
	"\f_description\"@\n" +
	"\x18CreateNewProductResponse\x12$\n" +
	"\x0enew_product_id\x18\x01 \x01(\tR\fnewProductId\" \n" +
	"\bNewPhoto\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"=\n" +
	"\x13OrderSessionRequest\x12&\n" +
	"\ashop_id\x18\x01 \x01(\v2\r.uuid.v1.UuIdR\x06shopId\"\x8f\x01\n" +
	"\fOrderSession\x12#\n" +
	"\rorder_subject\x18\x01 \x01(\tR\forderSubject\x12\x1f\n" +
	"\vorder_token\x18\x02 \x01(\tR\n" +
	"orderToken\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt*#\n" +
	"\vContactType\x12\t\n" +
	"\x05email\x10\x00\x12\t\n" +
	"\x05phone\x10\x01*a\n" +
	"\x03Day\x12\n" +
	"\n" +
	"\x06monday\x10\x00\x12\v\n" +
	"\atuesday\x10\x01\x12\r\n" +
	"\twednesday\x10\x02\x12\f\n" +
	"\bthursday\x10\x03\x12\n" +
	"\n" +
	"\x06friday\x10\x04\x12\f\n" +
	"\bsaturday\x10\x05\x12\n" +
	"\n" +
	"\x06sunday\x10\x06*+\n" +
	"\x10ShopDeviceStatus\x12\n" +
	"\n" +
	"\x06online\x10\x00\x12\v\n" +
	"\aoffline\x10\x01*9\n" +
	"\rServingMethod\x12\v\n" +
	"\adine_in\x10\x00\x12\r\n" +
	"\ttake_away\x10\x01\x12\f\n" +
	"\bdelivery\x10\x022\xb1\x04\n" +
	"\vShopService\x12M\n" +
	"\rCreateNewShop\x12\x1d.shop.v1.CreateNewShopRequest\x1a\x1d.shop.v1.CreateNewShopRequest\x12?\n" +
	"\bGetShops\x12\x18.shop.v1.GetShopsRequest\x1a\x19.shop.v1.GetShopsResponse\x12W\n" +
	"\x10ShopDeviceStatus\x12 .shop.v1.ShopDeviceStatusRequest\x1a!.shop.v1.ShopDeviceStatusResponse\x12?\n" +
	"\bOpenShop\x12\x18.shop.v1.OpenShopRequest\x1a\x19.shop.v1.OpenShopResponse\x12B\n" +
	"\tCloseShop\x12\x19.shop.v1.CloseShopRequest\x1a\x1a.shop.v1.CloseShopResponse\x12l\n" +
	"\x17UpdateOrderAccessConfig\x12'.shop.v1.UpdateOrderAccessConfigRequest\x1a(.shop.v1.UpdateOrderAccessConfigResponse\x12F\n" +
	"\x0fGetOrderSession\x12\x1c.shop.v1.OrderSessionRequest\x1a\x15.shop.v1.OrderSessionB\x06Z\x04./v1b\x06proto3"

var (
	file_shop_v1_shop_proto_rawDescOnce sync.Once
	file_shop_v1_shop_proto_rawDescData []byte
)

func file_shop_v1_shop_proto_rawDescGZIP() []byte {
	file_shop_v1_shop_proto_rawDescOnce.Do(func() {
		file_shop_v1_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_v1_shop_proto_rawDesc), len(file_shop_v1_shop_proto_rawDesc)))
	})
	return file_shop_v1_shop_proto_rawDescData
}

var file_shop_v1_shop_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_shop_v1_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_shop_v1_shop_proto_goTypes = []any{
	(ContactType)(0),                        // 0: shop.v1.ContactType
	(Day)(0),                                // 1: shop.v1.Day
	(ShopDeviceStatus)(0),                   // 2: shop.v1.ShopDeviceStatus
	(ServingMethod)(0),                      // 3: shop.v1.ServingMethod
	(*Contact)(nil),                         // 4: shop.v1.Contact
	(*OperationHour)(nil),                   // 5: shop.v1.OperationHour
	(*CreateNewShopRequest)(nil),            // 6: shop.v1.CreateNewShopRequest
	(*CreateNewShopResponse)(nil),           // 7: shop.v1.CreateNewShopResponse
	(*GetShopsRequest)(nil),                 // 8: shop.v1.GetShopsRequest
	(*ShopPb)(nil),                          // 9: shop.v1.ShopPb
	(*RolePb)(nil),                          // 10: shop.v1.RolePb
	(*ShopRole)(nil),                        // 11: shop.v1.ShopRole
	(*GetShopsResponse)(nil),                // 12: shop.v1.GetShopsResponse
	(*ShopDeviceStatusRequest)(nil),         // 13: shop.v1.ShopDeviceStatusRequest
	(*ShopDeviceStatusResponse)(nil),        // 14: shop.v1.ShopDeviceStatusResponse
	(*OpenShopRequest)(nil),                 // 15: shop.v1.OpenShopRequest
	(*OpenShopResponse)(nil),                // 16: shop.v1.OpenShopResponse
	(*CloseShopRequest)(nil),                // 17: shop.v1.CloseShopRequest
	(*CloseShopResponse)(nil),               // 18: shop.v1.CloseShopResponse
	(*UpdateOrderAccessConfigRequest)(nil),  // 19: shop.v1.UpdateOrderAccessConfigRequest
	(*UpdateOrderAccessConfigResponse)(nil), // 20: shop.v1.UpdateOrderAccessConfigResponse
	(*Category)(nil),                        // 21: shop.v1.Category
	(*CreateNewProductRequest)(nil),         // 22: shop.v1.CreateNewProductRequest
	(*CreateNewProductResponse)(nil),        // 23: shop.v1.CreateNewProductResponse
	(*NewPhoto)(nil),                        // 24: shop.v1.NewPhoto
	(*OrderSessionRequest)(nil),             // 25: shop.v1.OrderSessionRequest
	(*OrderSession)(nil),                    // 26: shop.v1.OrderSession
	(*ReAuthRequest)(nil),                   // 27: auth.v1.ReAuthRequest
	(*UuId)(nil),                            // 28: uuid.v1.UuId
	(*timestamppb.Timestamp)(nil),           // 29: google.protobuf.Timestamp
	(*Session)(nil),                         // 30: auth.v1.Session
	(*PublicKeyOption)(nil),                 // 31: auth.v1.PublicKeyOption
	(*emptypb.Empty)(nil),                   // 32: google.protobuf.Empty
}
var file_shop_v1_shop_proto_depIdxs = []int32{
	0,  // 0: shop.v1.Contact.type:type_name -> shop.v1.ContactType
	4,  // 1: shop.v1.CreateNewShopRequest.contacts:type_name -> shop.v1.Contact
	5,  // 2: shop.v1.CreateNewShopRequest.opens_at:type_name -> shop.v1.OperationHour
	5,  // 3: shop.v1.CreateNewShopRequest.closes_at:type_name -> shop.v1.OperationHour
	1,  // 4: shop.v1.CreateNewShopRequest.operation_days:type_name -> shop.v1.Day
	27, // 5: shop.v1.CreateNewShopRequest.r_auth:type_name -> auth.v1.ReAuthRequest
	28, // 6: shop.v1.CreateNewShopResponse.shop_id:type_name -> uuid.v1.UuId
	29, // 7: shop.v1.CreateNewShopResponse.last_updated_at:type_name -> google.protobuf.Timestamp
	30, // 8: shop.v1.CreateNewShopResponse.fresh_session:type_name -> auth.v1.Session
	31, // 9: shop.v1.CreateNewShopResponse.options:type_name -> auth.v1.PublicKeyOption
	29, // 10: shop.v1.GetShopsRequest.last_requested_at:type_name -> google.protobuf.Timestamp
	27, // 11: shop.v1.GetShopsRequest.r_auth:type_name -> auth.v1.ReAuthRequest
	28, // 12: shop.v1.ShopPb.shop_id:type_name -> uuid.v1.UuId
	5,  // 13: shop.v1.ShopPb.opens_at:type_name -> shop.v1.OperationHour
	5,  // 14: shop.v1.ShopPb.closes_at:type_name -> shop.v1.OperationHour
	4,  // 15: shop.v1.ShopPb.contacts:type_name -> shop.v1.Contact
	1,  // 16: shop.v1.ShopPb.operation_days:type_name -> shop.v1.Day
	28, // 17: shop.v1.RolePb.role_id:type_name -> uuid.v1.UuId
	9,  // 18: shop.v1.ShopRole.shop:type_name -> shop.v1.ShopPb
	10, // 19: shop.v1.ShopRole.role:type_name -> shop.v1.RolePb
	11, // 20: shop.v1.GetShopsResponse.shops:type_name -> shop.v1.ShopRole
	30, // 21: shop.v1.GetShopsResponse.fresh_session:type_name -> auth.v1.Session
	31, // 22: shop.v1.GetShopsResponse.options:type_name -> auth.v1.PublicKeyOption
	28, // 23: shop.v1.ShopDeviceStatusRequest.shop_id:type_name -> uuid.v1.UuId
	28, // 24: shop.v1.ShopDeviceStatusRequest.device_id:type_name -> uuid.v1.UuId
	2,  // 25: shop.v1.ShopDeviceStatusResponse.status:type_name -> shop.v1.ShopDeviceStatus
	28, // 26: shop.v1.OpenShopRequest.shop_id:type_name -> uuid.v1.UuId
	29, // 27: shop.v1.OpenShopRequest.open_until:type_name -> google.protobuf.Timestamp
	28, // 28: shop.v1.OpenShopRequest.device_id:type_name -> uuid.v1.UuId
	32, // 29: shop.v1.OpenShopResponse.ok:type_name -> google.protobuf.Empty
	28, // 30: shop.v1.CloseShopRequest.shop_id:type_name -> uuid.v1.UuId
	32, // 31: shop.v1.CloseShopResponse.ok:type_name -> google.protobuf.Empty
	3,  // 32: shop.v1.UpdateOrderAccessConfigRequest.serving_method:type_name -> shop.v1.ServingMethod
	32, // 33: shop.v1.UpdateOrderAccessConfigResponse.ok:type_name -> google.protobuf.Empty
	29, // 34: shop.v1.Category.available_from:type_name -> google.protobuf.Timestamp
	29, // 35: shop.v1.Category.available_until:type_name -> google.protobuf.Timestamp
	21, // 36: shop.v1.CreateNewProductRequest.categories:type_name -> shop.v1.Category
	28, // 37: shop.v1.OrderSessionRequest.shop_id:type_name -> uuid.v1.UuId
	29, // 38: shop.v1.OrderSession.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 39: shop.v1.ShopService.CreateNewShop:input_type -> shop.v1.CreateNewShopRequest
	8,  // 40: shop.v1.ShopService.GetShops:input_type -> shop.v1.GetShopsRequest
	13, // 41: shop.v1.ShopService.ShopDeviceStatus:input_type -> shop.v1.ShopDeviceStatusRequest
	15, // 42: shop.v1.ShopService.OpenShop:input_type -> shop.v1.OpenShopRequest
	17, // 43: shop.v1.ShopService.CloseShop:input_type -> shop.v1.CloseShopRequest
	19, // 44: shop.v1.ShopService.UpdateOrderAccessConfig:input_type -> shop.v1.UpdateOrderAccessConfigRequest
	25, // 45: shop.v1.ShopService.GetOrderSession:input_type -> shop.v1.OrderSessionRequest
	6,  // 46: shop.v1.ShopService.CreateNewShop:output_type -> shop.v1.CreateNewShopRequest
	12, // 47: shop.v1.ShopService.GetShops:output_type -> shop.v1.GetShopsResponse
	14, // 48: shop.v1.ShopService.ShopDeviceStatus:output_type -> shop.v1.ShopDeviceStatusResponse
	16, // 49: shop.v1.ShopService.OpenShop:output_type -> shop.v1.OpenShopResponse
	18, // 50: shop.v1.ShopService.CloseShop:output_type -> shop.v1.CloseShopResponse
	20, // 51: shop.v1.ShopService.UpdateOrderAccessConfig:output_type -> shop.v1.UpdateOrderAccessConfigResponse
	26, // 52: shop.v1.ShopService.GetOrderSession:output_type -> shop.v1.OrderSession
	46, // [46:53] is the sub-list for method output_type
	39, // [39:46] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_shop_v1_shop_proto_init() }
func file_shop_v1_shop_proto_init() {
	if File_shop_v1_shop_proto != nil {
		return
	}
	file_auth_v1_auth_proto_init()
	file_uuid_v1_uuid_proto_init()
	file_shop_v1_shop_proto_msgTypes[2].OneofWrappers = []any{}
	file_shop_v1_shop_proto_msgTypes[3].OneofWrappers = []any{}
	file_shop_v1_shop_proto_msgTypes[4].OneofWrappers = []any{}
	file_shop_v1_shop_proto_msgTypes[5].OneofWrappers = []any{}
	file_shop_v1_shop_proto_msgTypes[7].OneofWrappers = []any{}
	file_shop_v1_shop_proto_msgTypes[8].OneofWrappers = []any{}
	file_shop_v1_shop_proto_msgTypes[11].OneofWrappers = []any{}
	file_shop_v1_shop_proto_msgTypes[15].OneofWrappers = []any{}
	file_shop_v1_shop_proto_msgTypes[17].OneofWrappers = []any{}
	file_shop_v1_shop_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_v1_shop_proto_rawDesc), len(file_shop_v1_shop_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_v1_shop_proto_goTypes,
		DependencyIndexes: file_shop_v1_shop_proto_depIdxs,
		EnumInfos:         file_shop_v1_shop_proto_enumTypes,
		MessageInfos:      file_shop_v1_shop_proto_msgTypes,
	}.Build()
	File_shop_v1_shop_proto = out.File
	file_shop_v1_shop_proto_goTypes = nil
	file_shop_v1_shop_proto_depIdxs = nil
}
