// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: shop/v1/shop.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShopService_CreateNewShop_FullMethodName           = "/shop.v1.ShopService/CreateNewShop"
	ShopService_GetShops_FullMethodName                = "/shop.v1.ShopService/GetShops"
	ShopService_ShopDeviceStatus_FullMethodName        = "/shop.v1.ShopService/ShopDeviceStatus"
	ShopService_OpenShop_FullMethodName                = "/shop.v1.ShopService/OpenShop"
	ShopService_CloseShop_FullMethodName               = "/shop.v1.ShopService/CloseShop"
	ShopService_UpdateOrderAccessConfig_FullMethodName = "/shop.v1.ShopService/UpdateOrderAccessConfig"
	ShopService_GetOrderSession_FullMethodName         = "/shop.v1.ShopService/GetOrderSession"
)

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopServiceClient interface {
	CreateNewShop(ctx context.Context, in *CreateNewShopRequest, opts ...grpc.CallOption) (*CreateNewShopRequest, error)
	GetShops(ctx context.Context, in *GetShopsRequest, opts ...grpc.CallOption) (*GetShopsResponse, error)
	ShopDeviceStatus(ctx context.Context, in *ShopDeviceStatusRequest, opts ...grpc.CallOption) (*ShopDeviceStatusResponse, error)
	OpenShop(ctx context.Context, in *OpenShopRequest, opts ...grpc.CallOption) (*OpenShopResponse, error)
	CloseShop(ctx context.Context, in *CloseShopRequest, opts ...grpc.CallOption) (*CloseShopResponse, error)
	UpdateOrderAccessConfig(ctx context.Context, in *UpdateOrderAccessConfigRequest, opts ...grpc.CallOption) (*UpdateOrderAccessConfigResponse, error)
	// NOTE: [INFO] to revise or decide to scratch off
	GetOrderSession(ctx context.Context, in *OrderSessionRequest, opts ...grpc.CallOption) (*OrderSession, error)
}

type shopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopServiceClient(cc grpc.ClientConnInterface) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) CreateNewShop(ctx context.Context, in *CreateNewShopRequest, opts ...grpc.CallOption) (*CreateNewShopRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewShopRequest)
	err := c.cc.Invoke(ctx, ShopService_CreateNewShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetShops(ctx context.Context, in *GetShopsRequest, opts ...grpc.CallOption) (*GetShopsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShopsResponse)
	err := c.cc.Invoke(ctx, ShopService_GetShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ShopDeviceStatus(ctx context.Context, in *ShopDeviceStatusRequest, opts ...grpc.CallOption) (*ShopDeviceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopDeviceStatusResponse)
	err := c.cc.Invoke(ctx, ShopService_ShopDeviceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) OpenShop(ctx context.Context, in *OpenShopRequest, opts ...grpc.CallOption) (*OpenShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenShopResponse)
	err := c.cc.Invoke(ctx, ShopService_OpenShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) CloseShop(ctx context.Context, in *CloseShopRequest, opts ...grpc.CallOption) (*CloseShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseShopResponse)
	err := c.cc.Invoke(ctx, ShopService_CloseShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UpdateOrderAccessConfig(ctx context.Context, in *UpdateOrderAccessConfigRequest, opts ...grpc.CallOption) (*UpdateOrderAccessConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrderAccessConfigResponse)
	err := c.cc.Invoke(ctx, ShopService_UpdateOrderAccessConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetOrderSession(ctx context.Context, in *OrderSessionRequest, opts ...grpc.CallOption) (*OrderSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderSession)
	err := c.cc.Invoke(ctx, ShopService_GetOrderSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
// All implementations must embed UnimplementedShopServiceServer
// for forward compatibility.
type ShopServiceServer interface {
	CreateNewShop(context.Context, *CreateNewShopRequest) (*CreateNewShopRequest, error)
	GetShops(context.Context, *GetShopsRequest) (*GetShopsResponse, error)
	ShopDeviceStatus(context.Context, *ShopDeviceStatusRequest) (*ShopDeviceStatusResponse, error)
	OpenShop(context.Context, *OpenShopRequest) (*OpenShopResponse, error)
	CloseShop(context.Context, *CloseShopRequest) (*CloseShopResponse, error)
	UpdateOrderAccessConfig(context.Context, *UpdateOrderAccessConfigRequest) (*UpdateOrderAccessConfigResponse, error)
	// NOTE: [INFO] to revise or decide to scratch off
	GetOrderSession(context.Context, *OrderSessionRequest) (*OrderSession, error)
	mustEmbedUnimplementedShopServiceServer()
}

// UnimplementedShopServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShopServiceServer struct{}

func (UnimplementedShopServiceServer) CreateNewShop(context.Context, *CreateNewShopRequest) (*CreateNewShopRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewShop not implemented")
}
func (UnimplementedShopServiceServer) GetShops(context.Context, *GetShopsRequest) (*GetShopsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShops not implemented")
}
func (UnimplementedShopServiceServer) ShopDeviceStatus(context.Context, *ShopDeviceStatusRequest) (*ShopDeviceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShopDeviceStatus not implemented")
}
func (UnimplementedShopServiceServer) OpenShop(context.Context, *OpenShopRequest) (*OpenShopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenShop not implemented")
}
func (UnimplementedShopServiceServer) CloseShop(context.Context, *CloseShopRequest) (*CloseShopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseShop not implemented")
}
func (UnimplementedShopServiceServer) UpdateOrderAccessConfig(context.Context, *UpdateOrderAccessConfigRequest) (*UpdateOrderAccessConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderAccessConfig not implemented")
}
func (UnimplementedShopServiceServer) GetOrderSession(context.Context, *OrderSessionRequest) (*OrderSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderSession not implemented")
}
func (UnimplementedShopServiceServer) mustEmbedUnimplementedShopServiceServer() {}
func (UnimplementedShopServiceServer) testEmbeddedByValue()                     {}

// UnsafeShopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopServiceServer will
// result in compilation errors.
type UnsafeShopServiceServer interface {
	mustEmbedUnimplementedShopServiceServer()
}

func RegisterShopServiceServer(s grpc.ServiceRegistrar, srv ShopServiceServer) {
	// If the following call pancis, it indicates UnimplementedShopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShopService_ServiceDesc, srv)
}

func _ShopService_CreateNewShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).CreateNewShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_CreateNewShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).CreateNewShop(ctx, req.(*CreateNewShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetShops(ctx, req.(*GetShopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ShopDeviceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopDeviceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ShopDeviceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ShopDeviceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ShopDeviceStatus(ctx, req.(*ShopDeviceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_OpenShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).OpenShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_OpenShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).OpenShop(ctx, req.(*OpenShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_CloseShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).CloseShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_CloseShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).CloseShop(ctx, req.(*CloseShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UpdateOrderAccessConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderAccessConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).UpdateOrderAccessConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_UpdateOrderAccessConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).UpdateOrderAccessConfig(ctx, req.(*UpdateOrderAccessConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetOrderSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetOrderSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetOrderSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetOrderSession(ctx, req.(*OrderSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopService_ServiceDesc is the grpc.ServiceDesc for ShopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shop.v1.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewShop",
			Handler:    _ShopService_CreateNewShop_Handler,
		},
		{
			MethodName: "GetShops",
			Handler:    _ShopService_GetShops_Handler,
		},
		{
			MethodName: "ShopDeviceStatus",
			Handler:    _ShopService_ShopDeviceStatus_Handler,
		},
		{
			MethodName: "OpenShop",
			Handler:    _ShopService_OpenShop_Handler,
		},
		{
			MethodName: "CloseShop",
			Handler:    _ShopService_CloseShop_Handler,
		},
		{
			MethodName: "UpdateOrderAccessConfig",
			Handler:    _ShopService_UpdateOrderAccessConfig_Handler,
		},
		{
			MethodName: "GetOrderSession",
			Handler:    _ShopService_GetOrderSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop/v1/shop.proto",
}
